fn main() {
    panic!("error happen!")
}
